name: notes_restapi
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_staggered_grid_view: ^0.6.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^3.1.1
  google_fonts: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  share_plus: ^4.0.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
